import { BikeSpecs } from './physics';

export interface SavedBike {
  id?: string;
  name: string;
  specs: BikeSpecs;
  image?: string;
}

export const STANDARD_BIKES: SavedBike[] = [
  // --- High Performance E-Motos & Motorcycles ---
  { name: "Surron Light Bee X (2025)", specs: { voltage: 60, capacityAh: 40, motorWatts: 8000, bikeWeightLbs: 125 } },
  { name: "Surron Ultra Bee", specs: { voltage: 74, capacityAh: 55, motorWatts: 12500, bikeWeightLbs: 187 } },
  { name: "Surron Storm Bee", specs: { voltage: 90, capacityAh: 55, motorWatts: 22500, bikeWeightLbs: 280 } },
  { name: "Talaria Sting R MX4", specs: { voltage: 60, capacityAh: 45, motorWatts: 8000, bikeWeightLbs: 145 } },
  { name: "Talaria Sting MX5 Pro", specs: { voltage: 72, capacityAh: 40, motorWatts: 13400, bikeWeightLbs: 167 } },
  { name: "Talaria X3 (XXX)", specs: { voltage: 60, capacityAh: 40, motorWatts: 6500, bikeWeightLbs: 125 } },
  { name: "Talaria Dragon", specs: { voltage: 88, capacityAh: 60, motorWatts: 28000, bikeWeightLbs: 220 } },
  { name: "Stark Varg Alpha", specs: { voltage: 360, capacityAh: 18, motorWatts: 60000, bikeWeightLbs: 260 } },
  { name: "Zero SR/F", specs: { voltage: 102, capacityAh: 170, motorWatts: 82000, bikeWeightLbs: 500 } },
  { name: "Zero DSR/X", specs: { voltage: 102, capacityAh: 170, motorWatts: 75000, bikeWeightLbs: 545 } },
  { name: "Zero FX", specs: { voltage: 102, capacityAh: 70, motorWatts: 34000, bikeWeightLbs: 289 } },
  { name: "Energica Ego+ RS", specs: { voltage: 300, capacityAh: 72, motorWatts: 126000, bikeWeightLbs: 573 } },
  { name: "Energica Experia", specs: { voltage: 300, capacityAh: 75, motorWatts: 75000, bikeWeightLbs: 573 } },
  { name: "LiveWire One", specs: { voltage: 350, capacityAh: 44, motorWatts: 75000, bikeWeightLbs: 562 } },
  { name: "LiveWire S2 Del Mar", specs: { voltage: 102, capacityAh: 103, motorWatts: 63000, bikeWeightLbs: 436 } },
  { name: "E Ride Pro SS", specs: { voltage: 72, capacityAh: 40, motorWatts: 12000, bikeWeightLbs: 139 } },
  { name: "Cake Bukk", specs: { voltage: 72, capacityAh: 40, motorWatts: 16000, bikeWeightLbs: 196 } },
  { name: "Cake Kalk OR", specs: { voltage: 52, capacityAh: 50, motorWatts: 11000, bikeWeightLbs: 165 } },
  { name: "UBCO 2x2 Adventure", specs: { voltage: 50, capacityAh: 62, motorWatts: 2000, bikeWeightLbs: 156 } },
  { name: "Onyx RCR", specs: { voltage: 72, capacityAh: 41, motorWatts: 5000, bikeWeightLbs: 145 } },

  // --- Premium & Lightweight E-Bikes ---
  { name: "Specialized Turbo Levo (Gen 3)", specs: { voltage: 36, capacityAh: 19.4, motorWatts: 565, bikeWeightLbs: 50 } },
  { name: "Specialized Turbo Levo SL 2", specs: { voltage: 48, capacityAh: 6.6, motorWatts: 320, bikeWeightLbs: 39 } },
  { name: "Specialized Turbo Vado 5.0", specs: { voltage: 36, capacityAh: 19.7, motorWatts: 565, bikeWeightLbs: 58 } },
  { name: "Specialized Turbo Creo 2", specs: { voltage: 48, capacityAh: 6.6, motorWatts: 320, bikeWeightLbs: 30 } },
  { name: "Specialized Turbo Porto", specs: { voltage: 36, capacityAh: 19.7, motorWatts: 565, bikeWeightLbs: 85 } },
  { name: "Trek Fuel EXe", specs: { voltage: 50, capacityAh: 7.2, motorWatts: 250, bikeWeightLbs: 41 } },
  { name: "Trek Rail 9.9", specs: { voltage: 36, capacityAh: 20.8, motorWatts: 250, bikeWeightLbs: 49 } },
  { name: "Trek Allant+ 9.9s", specs: { voltage: 36, capacityAh: 17.3, motorWatts: 250, bikeWeightLbs: 51 } },
  { name: "Giant Trance X Advanced E+ Elite", specs: { voltage: 36, capacityAh: 11.1, motorWatts: 250, bikeWeightLbs: 42 } },
  { name: "Giant Reign E+", specs: { voltage: 36, capacityAh: 22.2, motorWatts: 250, bikeWeightLbs: 54 } },
  { name: "Giant Revolt E+", specs: { voltage: 36, capacityAh: 13.8, motorWatts: 250, bikeWeightLbs: 40 } },
  { name: "Santa Cruz Heckler", specs: { voltage: 36, capacityAh: 20, motorWatts: 250, bikeWeightLbs: 48 } },
  { name: "Yeti 160E", specs: { voltage: 36, capacityAh: 17.5, motorWatts: 250, bikeWeightLbs: 52 } },
  { name: "Gazelle Eclipse C380", specs: { voltage: 36, capacityAh: 20.8, motorWatts: 250, bikeWeightLbs: 59 } },
  { name: "Tern Orox", specs: { voltage: 36, capacityAh: 22.2, motorWatts: 250, bikeWeightLbs: 74 } },
  { name: "Tern GSD S00", specs: { voltage: 36, capacityAh: 13.8, motorWatts: 250, bikeWeightLbs: 82 } },
  { name: "Canyon Strive:ON", specs: { voltage: 36, capacityAh: 20.8, motorWatts: 600, bikeWeightLbs: 53 } },
  { name: "Orbea Rise LT", specs: { voltage: 36, capacityAh: 11.6, motorWatts: 250, bikeWeightLbs: 37 } },
  { name: "Rocky Mountain Altitude Powerplay", specs: { voltage: 48, capacityAh: 15, motorWatts: 700, bikeWeightLbs: 54 } },
  { name: "Cannondale Moterra Neo", specs: { voltage: 36, capacityAh: 20.8, motorWatts: 250, bikeWeightLbs: 55 } },

  // --- Commuter & Everyday Utility ---
  { name: "Aventon Aventure.3", specs: { voltage: 48, capacityAh: 15, motorWatts: 750, bikeWeightLbs: 77 } },
  { name: "Aventon Level.2", specs: { voltage: 48, capacityAh: 14, motorWatts: 500, bikeWeightLbs: 62 } },
  { name: "Aventon Soltera.2", specs: { voltage: 36, capacityAh: 9.6, motorWatts: 350, bikeWeightLbs: 46 } },
  { name: "Aventon Abound", specs: { voltage: 48, capacityAh: 15, motorWatts: 750, bikeWeightLbs: 81 } },
  { name: "Rad Power Radster Road", specs: { voltage: 48, capacityAh: 15, motorWatts: 750, bikeWeightLbs: 75 } },
  { name: "Rad Power RadWagon 5", specs: { voltage: 48, capacityAh: 15, motorWatts: 750, bikeWeightLbs: 86 } },
  { name: "Rad Power RadRunner 3 Plus", specs: { voltage: 48, capacityAh: 14, motorWatts: 750, bikeWeightLbs: 75 } },
  { name: "Rad Power RadExpand 5 Plus", specs: { voltage: 48, capacityAh: 15, motorWatts: 750, bikeWeightLbs: 72 } },
  { name: "Lectric XP 3.0", specs: { voltage: 48, capacityAh: 10.4, motorWatts: 500, bikeWeightLbs: 64 } },
  { name: "Lectric ONE", specs: { voltage: 48, capacityAh: 14, motorWatts: 750, bikeWeightLbs: 55 } },
  { name: "Lectric XPeak", specs: { voltage: 48, capacityAh: 14, motorWatts: 750, bikeWeightLbs: 71 } },
  { name: "Ride1Up Revv 1 DRT", specs: { voltage: 52, capacityAh: 20, motorWatts: 750, bikeWeightLbs: 93 } },
  { name: "Ride1Up Portola", specs: { voltage: 48, capacityAh: 13.4, motorWatts: 750, bikeWeightLbs: 59 } },
  { name: "Juiced Scrambler FS", specs: { voltage: 52, capacityAh: 19.2, motorWatts: 750, bikeWeightLbs: 78 } },
  { name: "Juiced Scorpion X2", specs: { voltage: 52, capacityAh: 15.6, motorWatts: 1000, bikeWeightLbs: 77 } },
  { name: "Super73-S2 Legacy", specs: { voltage: 48, capacityAh: 20, motorWatts: 750, bikeWeightLbs: 73 } },
  { name: "Super73-R Adventure", specs: { voltage: 48, capacityAh: 20, motorWatts: 1000, bikeWeightLbs: 88 } },
  { name: "Himiway A7 Pro", specs: { voltage: 48, capacityAh: 15, motorWatts: 500, bikeWeightLbs: 65 } },
  { name: "Engwe X26", specs: { voltage: 48, capacityAh: 29.2, motorWatts: 1000, bikeWeightLbs: 90 } },
  { name: "Velotric Nomad 1", specs: { voltage: 48, capacityAh: 14.7, motorWatts: 750, bikeWeightLbs: 72 } },

  // --- Specialized & High Torque ---
  { name: "Wired Freedom", specs: { voltage: 60, capacityAh: 20, motorWatts: 2400, bikeWeightLbs: 88 } },
  { name: "Solar Eclipse 2.0", specs: { voltage: 72, capacityAh: 45, motorWatts: 10000, bikeWeightLbs: 130 } },
  { name: "Roadrunner Pro", specs: { voltage: 60, capacityAh: 30, motorWatts: 4000, bikeWeightLbs: 105 } },
  { name: "QuietKat Apex Pro", specs: { voltage: 48, capacityAh: 16, motorWatts: 1000, bikeWeightLbs: 70 } },
  { name: "Bakcou Mule", specs: { voltage: 48, capacityAh: 21, motorWatts: 1000, bikeWeightLbs: 68 } },
  { name: "VanMoof S5", specs: { voltage: 42, capacityAh: 11, motorWatts: 250, bikeWeightLbs: 50 } },
  { name: "Cowboy Cruiser", specs: { voltage: 36, capacityAh: 10, motorWatts: 250, bikeWeightLbs: 42 } },
  { name: "Propella 7S v4", specs: { voltage: 36, capacityAh: 7, motorWatts: 250, bikeWeightLbs: 37 } },
  { name: "Tenways CGO600 Pro", specs: { voltage: 36, capacityAh: 10, motorWatts: 250, bikeWeightLbs: 35 } },
  { name: "Blix Dubbel", specs: { voltage: 48, capacityAh: 14, motorWatts: 750, bikeWeightLbs: 70 } },
  { name: "Riese & M├╝ller Load 75", specs: { voltage: 36, capacityAh: 27.7, motorWatts: 250, bikeWeightLbs: 84 } },
  { name: "Flyer L885 (Radio Flyer)", specs: { voltage: 48, capacityAh: 15, motorWatts: 500, bikeWeightLbs: 73 } },
  { name: "Biktrix Juggernaut", specs: { voltage: 52, capacityAh: 17.5, motorWatts: 1000, bikeWeightLbs: 75 } },
  { name: "Luna Sur-Ron X", specs: { voltage: 60, capacityAh: 32, motorWatts: 6000, bikeWeightLbs: 110 } },
  { name: "Fiido Titan", specs: { voltage: 48, capacityAh: 14.5, motorWatts: 750, bikeWeightLbs: 65 } },
  { name: "Heybike Mars 2.0", specs: { voltage: 48, capacityAh: 12.5, motorWatts: 750, bikeWeightLbs: 66 } },
  { name: "Gotrax Tundra", specs: { voltage: 48, capacityAh: 20, motorWatts: 750, bikeWeightLbs: 75 } },
  { name: "Mokwheel Basalt", specs: { voltage: 48, capacityAh: 19.6, motorWatts: 750, bikeWeightLbs: 79 } },
  { name: "Denago Commute 1", specs: { voltage: 48, capacityAh: 13.6, motorWatts: 500, bikeWeightLbs: 62 } },
  { name: "Wallke H6", specs: { voltage: 48, capacityAh: 35, motorWatts: 750, bikeWeightLbs: 90 } },

  // --- Utility & Value ---
  { name: "Bafang BBSHD Custom Build", specs: { voltage: 52, capacityAh: 17.5, motorWatts: 1000, bikeWeightLbs: 65 } },
  { name: "Vvolt Centauri", specs: { voltage: 36, capacityAh: 10.4, motorWatts: 250, bikeWeightLbs: 48 } },
  { name: "Priority Current", specs: { voltage: 48, capacityAh: 10.4, motorWatts: 500, bikeWeightLbs: 53 } },
  { name: "FLX Baby Maker II", specs: { voltage: 36, capacityAh: 10, motorWatts: 350, bikeWeightLbs: 35 } },
  { name: "Ariel Rider Kepler", specs: { voltage: 52, capacityAh: 20, motorWatts: 1000, bikeWeightLbs: 73 } },
  { name: "Ariel Rider Grizzly", specs: { voltage: 52, capacityAh: 35, motorWatts: 2000, bikeWeightLbs: 105 } },
  { name: "Ride1Up LMT'D", specs: { voltage: 48, capacityAh: 14, motorWatts: 750, bikeWeightLbs: 53 } },
  { name: "Sondors MadMod (2024)", specs: { voltage: 48, capacityAh: 21, motorWatts: 750, bikeWeightLbs: 80 } },
  { name: "Wing Freedom 2", specs: { voltage: 36, capacityAh: 14, motorWatts: 350, bikeWeightLbs: 39 } },
  { name: "Eurowheel X1", specs: { voltage: 48, capacityAh: 15, motorWatts: 750, bikeWeightLbs: 65 } },
  { name: "Trojan Horse", specs: { voltage: 72, capacityAh: 30, motorWatts: 5000, bikeWeightLbs: 135 } },
  { name: "Monday Motorbikes Anza", specs: { voltage: 48, capacityAh: 14, motorWatts: 750, bikeWeightLbs: 65 } },
  { name: "Super73-Z1", specs: { voltage: 36, capacityAh: 11.6, motorWatts: 500, bikeWeightLbs: 56 } },
  { name: "Lectric XP Lite 2.0", specs: { voltage: 48, capacityAh: 7.8, motorWatts: 300, bikeWeightLbs: 47 } },
  { name: "Aventon Sinch.2", specs: { voltage: 48, capacityAh: 14, motorWatts: 500, bikeWeightLbs: 68 } },
  { name: "Eunorau Fat-HS", specs: { voltage: 48, capacityAh: 14, motorWatts: 1000, bikeWeightLbs: 80 } },
  { name: "Magicycle Deer", specs: { voltage: 52, capacityAh: 20, motorWatts: 750, bikeWeightLbs: 92 } },
  { name: "KBO Breeze", specs: { voltage: 48, capacityAh: 16, motorWatts: 500, bikeWeightLbs: 62 } },
  { name: "Himiway Zebra", specs: { voltage: 48, capacityAh: 20, motorWatts: 750, bikeWeightLbs: 79 } },
  { name: "Rad Power RadRover 6 Plus", specs: { voltage: 48, capacityAh: 14, motorWatts: 750, bikeWeightLbs: 73 } },

  // --- ELECTRIC SCOOTERS: Commuter & Portable ---
  { name: "Segway Ninebot Max G2", specs: { voltage: 36, capacityAh: 15.3, motorWatts: 450, bikeWeightLbs: 53 } },
  { name: "Segway Ninebot Max G30P", specs: { voltage: 36, capacityAh: 15.3, motorWatts: 350, bikeWeightLbs: 42 } },
  { name: "NIU KQi3 Max", specs: { voltage: 48, capacityAh: 13, motorWatts: 450, bikeWeightLbs: 46 } },
  { name: "NIU KQi3 Pro", specs: { voltage: 48, capacityAh: 10, motorWatts: 350, bikeWeightLbs: 44 } },
  { name: "NIU KQi Air (Carbon)", specs: { voltage: 48, capacityAh: 9.4, motorWatts: 350, bikeWeightLbs: 26 } },
  { name: "Apollo Go", specs: { voltage: 36, capacityAh: 15, motorWatts: 700, bikeWeightLbs: 46 } },
  { name: "Apollo Air 2024", specs: { voltage: 36, capacityAh: 10, motorWatts: 350, bikeWeightLbs: 38 } },
  { name: "VMAX VX2 Pro GT", specs: { voltage: 48, capacityAh: 16.5, motorWatts: 500, bikeWeightLbs: 45 } },
  { name: "Fluid Mosquito", specs: { voltage: 48, capacityAh: 9.6, motorWatts: 500, bikeWeightLbs: 29 } },
  { name: "Unagi Model One Voyager", specs: { voltage: 36, capacityAh: 10, motorWatts: 500, bikeWeightLbs: 29 } },
  { name: "Gotrax G5", specs: { voltage: 48, capacityAh: 9.6, motorWatts: 500, bikeWeightLbs: 44 } },
  { name: "Hiboy S2 Pro", specs: { voltage: 36, capacityAh: 11.6, motorWatts: 500, bikeWeightLbs: 36 } },
  { name: "Xiaomi Scooter 4 Pro", specs: { voltage: 36, capacityAh: 12.4, motorWatts: 350, bikeWeightLbs: 37 } },
  { name: "Segway F2 Pro", specs: { voltage: 36, capacityAh: 12.8, motorWatts: 450, bikeWeightLbs: 41 } },
  { name: "Inmotion S1F", specs: { voltage: 54, capacityAh: 12.5, motorWatts: 500, bikeWeightLbs: 53 } },
  { name: "Navee S65", specs: { voltage: 48, capacityAh: 12.7, motorWatts: 500, bikeWeightLbs: 54 } },
  { name: "Okai Neon Ultra", specs: { voltage: 48, capacityAh: 14.7, motorWatts: 500, bikeWeightLbs: 52 } },
  { name: "TurboAnt X7 Max", specs: { voltage: 36, capacityAh: 10, motorWatts: 350, bikeWeightLbs: 34 } },
  { name: "Pure Advance Plus", specs: { voltage: 37, capacityAh: 12, motorWatts: 500, bikeWeightLbs: 35 } },

  // --- ELECTRIC SCOOTERS: Performance & Long Range ---
  { name: "EMOVE Cruiser S", specs: { voltage: 52, capacityAh: 30, motorWatts: 1000, bikeWeightLbs: 52 } },
  { name: "Apollo City Pro 2024", specs: { voltage: 48, capacityAh: 20, motorWatts: 1000, bikeWeightLbs: 65 } },
  { name: "Apollo Phantom V3", specs: { voltage: 52, capacityAh: 23, motorWatts: 1200, bikeWeightLbs: 77 } },
  { name: "Kaabo Mantis King GT", specs: { voltage: 60, capacityAh: 24, motorWatts: 1100, bikeWeightLbs: 74 } },
  { name: "Kaabo Mantis 10 Lite", specs: { voltage: 48, capacityAh: 13, motorWatts: 800, bikeWeightLbs: 55 } },
  { name: "Vsett 10+ (25.6Ah)", specs: { voltage: 60, capacityAh: 25.6, motorWatts: 1400, bikeWeightLbs: 79 } },
  { name: "Vsett 9+ (21Ah)", specs: { voltage: 48, capacityAh: 21, motorWatts: 650, bikeWeightLbs: 55 } },
  { name: "Dualtron Victor Luxury", specs: { voltage: 60, capacityAh: 24, motorWatts: 4000, bikeWeightLbs: 73 } },
  { name: "Dualtron Eagle Pro", specs: { voltage: 60, capacityAh: 22.4, motorWatts: 3600, bikeWeightLbs: 66 } },
  { name: "Nami Klima Max", specs: { voltage: 60, capacityAh: 30, motorWatts: 1000, bikeWeightLbs: 79 } },
  { name: "Inmotion Climber", specs: { voltage: 36, capacityAh: 14.7, motorWatts: 900, bikeWeightLbs: 46 } },
  { name: "Segway GT1", specs: { voltage: 48, capacityAh: 20, motorWatts: 1500, bikeWeightLbs: 101 } },
  { name: "Solar P1 3.0", specs: { voltage: 52, capacityAh: 18, motorWatts: 1200, bikeWeightLbs: 57 } },
  { name: "Varla Eagle One V2.0", specs: { voltage: 52, capacityAh: 20.8, motorWatts: 1000, bikeWeightLbs: 82 } },
  { name: "Teverun Blade Mini Pro", specs: { voltage: 48, capacityAh: 15.6, motorWatts: 500, bikeWeightLbs: 55 } },
  { name: "Yume Swift", specs: { voltage: 48, capacityAh: 22.5, motorWatts: 1200, bikeWeightLbs: 60 } },
  { name: "Kukirin G2 Master", specs: { voltage: 52, capacityAh: 20.8, motorWatts: 1000, bikeWeightLbs: 73 } },
  { name: "Joyor S10-S", specs: { voltage: 60, capacityAh: 18, motorWatts: 1000, bikeWeightLbs: 59 } },
  { name: "Nanrobot D6+", specs: { voltage: 52, capacityAh: 26, motorWatts: 1000, bikeWeightLbs: 77 } },
  { name: "Nanrobot Lightning", specs: { voltage: 48, capacityAh: 18, motorWatts: 800, bikeWeightLbs: 65 } },

  // --- HYPER SCOOTERS: Ultra Performance ---
  { name: "Dualtron X Limited", specs: { voltage: 84, capacityAh: 60, motorWatts: 2000, bikeWeightLbs: 183 } },
  { name: "Dualtron Thunder 3", specs: { voltage: 72, capacityAh: 40, motorWatts: 2500, bikeWeightLbs: 126 } },
  { name: "Dualtron Storm Limited", specs: { voltage: 84, capacityAh: 45, motorWatts: 2500, bikeWeightLbs: 111 } },
  { name: "Kaabo Wolf King GTR", specs: { voltage: 72, capacityAh: 35, motorWatts: 2000, bikeWeightLbs: 139 } },
  { name: "Kaabo Wolf Warrior 11 GT", specs: { voltage: 60, capacityAh: 35, motorWatts: 1200, bikeWeightLbs: 115 } },
  { name: "Nami Burn-E 2 Max", specs: { voltage: 72, capacityAh: 40, motorWatts: 1500, bikeWeightLbs: 103 } },
  { name: "Inmotion RS", specs: { voltage: 72, capacityAh: 40, motorWatts: 2000, bikeWeightLbs: 128 } },
  { name: "Teverun Fighter Supreme 7260R", specs: { voltage: 72, capacityAh: 60, motorWatts: 2500, bikeWeightLbs: 121 } },
  { name: "Segway GT2", specs: { voltage: 52, capacityAh: 30, motorWatts: 1500, bikeWeightLbs: 116 } },
  { name: "Apollo Pro 2024", specs: { voltage: 52, capacityAh: 30, motorWatts: 1200, bikeWeightLbs: 93 } },
  { name: "RoadRunner RX7", specs: { voltage: 72, capacityAh: 40, motorWatts: 1800, bikeWeightLbs: 130 } },
  { name: "Inokim OXO", specs: { voltage: 60, capacityAh: 25.6, motorWatts: 1000, bikeWeightLbs: 74 } },
  { name: "Vsett 11+ Super 72", specs: { voltage: 72, capacityAh: 35, motorWatts: 2000, bikeWeightLbs: 128 } },
  { name: "Weped Sonic X", specs: { voltage: 84, capacityAh: 50, motorWatts: 2500, bikeWeightLbs: 110 } },
  { name: "Rion Thrust", specs: { voltage: 84, capacityAh: 30, motorWatts: 2500, bikeWeightLbs: 64 } },
  { name: "Slack Core 920R", specs: { voltage: 72, capacityAh: 45, motorWatts: 2500, bikeWeightLbs: 105 } },
  { name: "Bronco Xtreme 11", specs: { voltage: 72, capacityAh: 35, motorWatts: 2500, bikeWeightLbs: 106 } },
  { name: "Yume X11+", specs: { voltage: 60, capacityAh: 31.5, motorWatts: 3000, bikeWeightLbs: 110 } },
  { name: "Solar P1 Pro", specs: { voltage: 60, capacityAh: 26, motorWatts: 2000, bikeWeightLbs: 85 } },
  { name: "Teverun Fighter Eleven+", specs: { voltage: 60, capacityAh: 35, motorWatts: 2500, bikeWeightLbs: 84 } },

  // --- ELECTRIC SCOOTERS: Off-Road & Specialized ---
  { name: "Bakcou Timberwolf", specs: { voltage: 48, capacityAh: 21, motorWatts: 750, bikeWeightLbs: 85 } },
  { name: "Gotrax GX3", specs: { voltage: 54, capacityAh: 25, motorWatts: 1000, bikeWeightLbs: 94 } },
  { name: "Kukirin G3 Pro", specs: { voltage: 52, capacityAh: 23, motorWatts: 1200, bikeWeightLbs: 88 } },
  { name: "OKAI Panther", specs: { voltage: 60, capacityAh: 25, motorWatts: 1000, bikeWeightLbs: 92 } },
  { name: "Dualtron City", specs: { voltage: 60, capacityAh: 25, motorWatts: 4000, bikeWeightLbs: 91 } },
  { name: "Solar EQ", specs: { voltage: 48, capacityAh: 20, motorWatts: 1000, bikeWeightLbs: 55 } },
  { name: "Teverun Fighter Mini", specs: { voltage: 52, capacityAh: 20, motorWatts: 1000, bikeWeightLbs: 65 } },
  { name: "Nami Burn-E 2 (Standard)", specs: { voltage: 72, capacityAh: 28, motorWatts: 1000, bikeWeightLbs: 100 } },
  { name: "Yume M11", specs: { voltage: 60, capacityAh: 31.5, motorWatts: 3500, bikeWeightLbs: 110 } },
  { name: "Dualtron Spider 2", specs: { voltage: 60, capacityAh: 24, motorWatts: 3900, bikeWeightLbs: 57 } },

  // --- SEATED SCOOTERS & INTERNATIONAL ---
  { name: "EMOVE RoadRunner Pro", specs: { voltage: 60, capacityAh: 30, motorWatts: 2000, bikeWeightLbs: 105 } },
  { name: "EMOVE RoadRunner SE", specs: { voltage: 48, capacityAh: 15, motorWatts: 500, bikeWeightLbs: 55 } },
  { name: "Ather 450 Apex", specs: { voltage: 51, capacityAh: 73, motorWatts: 7000, bikeWeightLbs: 238 } },
  { name: "Ola S1 Pro Gen 3", specs: { voltage: 72, capacityAh: 55, motorWatts: 11000, bikeWeightLbs: 275 } },
  { name: "Bajaj Chetak Premium", specs: { voltage: 50, capacityAh: 60, motorWatts: 4000, bikeWeightLbs: 290 } },
  { name: "TVS iQube ST", specs: { voltage: 52, capacityAh: 35, motorWatts: 4400, bikeWeightLbs: 291 } },
  { name: "Vespa Elettrica 70", specs: { voltage: 48, capacityAh: 86, motorWatts: 3600, bikeWeightLbs: 286 } },
  { name: "Razor EcoSmart Metro", specs: { voltage: 36, capacityAh: 7, motorWatts: 500, bikeWeightLbs: 67 } },
  { name: "Fiido Q1S", specs: { voltage: 36, capacityAh: 10, motorWatts: 250, bikeWeightLbs: 38 } },
  { name: "Cycleboard Rover", specs: { voltage: 60, capacityAh: 20, motorWatts: 1800, bikeWeightLbs: 83 } },

  // --- ADDITIONAL TOP MODELS ---
  { name: "Kaabo Mantis King GT", specs: { voltage: 60, capacityAh: 24, motorWatts: 1100, bikeWeightLbs: 74 } },
  { name: "Teverun Fighter Supreme 7260R", specs: { voltage: 72, capacityAh: 60, motorWatts: 2500, bikeWeightLbs: 121 } },
  { name: "Solar P1 Pro", specs: { voltage: 60, capacityAh: 26, motorWatts: 2000, bikeWeightLbs: 85 } },
  { name: "Apollo Dash", specs: { voltage: 36, capacityAh: 10, motorWatts: 350, bikeWeightLbs: 30 } },
  { name: "NIU KQi2 Pro", specs: { voltage: 36, capacityAh: 7.6, motorWatts: 300, bikeWeightLbs: 40 } },
  { name: "Gotrax G4", specs: { voltage: 36, capacityAh: 10.4, motorWatts: 350, bikeWeightLbs: 37 } },
  { name: "Gotrax GX1", specs: { voltage: 48, capacityAh: 15, motorWatts: 600, bikeWeightLbs: 76 } },
  { name: "VMAX VX5 Pro", specs: { voltage: 36, capacityAh: 7.8, motorWatts: 400, bikeWeightLbs: 35 } },
  { name: "TurboAnt M10 Lite", specs: { voltage: 36, capacityAh: 7.5, motorWatts: 350, bikeWeightLbs: 31 } },
  { name: "isinwheel S9 Pro", specs: { voltage: 36, capacityAh: 7.5, motorWatts: 350, bikeWeightLbs: 34 } },
  { name: "WERHY H7 Pro", specs: { voltage: 36, capacityAh: 10, motorWatts: 350, bikeWeightLbs: 33 } },
  { name: "Acer AES015 Series 5", specs: { voltage: 36, capacityAh: 15, motorWatts: 350, bikeWeightLbs: 41 } },
  { name: "OKAI Neon", specs: { voltage: 36, capacityAh: 9.8, motorWatts: 250, bikeWeightLbs: 35 } },
  { name: "Xiaomi Scooter 4 Ultra", specs: { voltage: 48, capacityAh: 12, motorWatts: 500, bikeWeightLbs: 54 } },
  { name: "Segway P100S", specs: { voltage: 48, capacityAh: 23, motorWatts: 650, bikeWeightLbs: 72 } },
  { name: "Apollo Phantom V2", specs: { voltage: 52, capacityAh: 23, motorWatts: 1200, bikeWeightLbs: 77 } },
  { name: "Dualtron Spider", specs: { voltage: 60, capacityAh: 17.5, motorWatts: 3000, bikeWeightLbs: 44 } },
  { name: "Kaabo Wolf Warrior X", specs: { voltage: 60, capacityAh: 21, motorWatts: 1100, bikeWeightLbs: 75 } },
  { name: "Inmotion L9", specs: { voltage: 54, capacityAh: 12.5, motorWatts: 500, bikeWeightLbs: 53 } },
  { name: "Joyor Y6-S", specs: { voltage: 48, capacityAh: 18, motorWatts: 500, bikeWeightLbs: 52 } },
  { name: "Yume S10", specs: { voltage: 48, capacityAh: 21, motorWatts: 1000, bikeWeightLbs: 60 } },
  { name: "Solar P1", specs: { voltage: 52, capacityAh: 18, motorWatts: 1200, bikeWeightLbs: 57 } }
  ];
interface POI {
export const PEDAL_EBIKES_US_UK_CA: SavedBike[] = [];
export const E_MOTOS_GLOBAL: SavedBike[] = [];
