export interface BikeSpecs {
  voltage: number | '';
  capacityAh: number | '';
  motorWatts: number | '';
  bikeWeightLbs: number | '';
  tirePSI?: number | '';
  tireType?: 'road' | 'knobby';
  driveMode?: 'throttle_only' | 'pas_only' | 'both';
  currentBatteryPercent?: number;
  controllerType?: string;
}

export interface SavedBike {
  id?: string;
  name: string;
  specs: BikeSpecs;
}

export const STANDARD_BIKES: SavedBike[] = [
  { name: "Surron Light Bee X (2025)", specs: { voltage: 60, capacityAh: 40, motorWatts: 8000, bikeWeightLbs: 125, tireType: 'knobby', controllerType: 'Sine Wave' } },
  { name: "Talaria Sting MX5 Pro", specs: { voltage: 72, capacityAh: 40, motorWatts: 13400, bikeWeightLbs: 167, tireType: 'knobby', controllerType: 'FOC' } },
  { name: "Onyx RCR", specs: { voltage: 72, capacityAh: 41, motorWatts: 5000, bikeWeightLbs: 145, tireType: 'road', controllerType: 'Kelly' } },
  { name: "Stark Varg Alpha", specs: { voltage: 360, capacityAh: 18, motorWatts: 60000, bikeWeightLbs: 260, tireType: 'knobby', controllerType: 'Proprietary FOC' } },
  { name: "Specialized Turbo Levo", specs: { voltage: 36, capacityAh: 19.4, motorWatts: 565, bikeWeightLbs: 50, tireType: 'knobby', controllerType: 'Brose' } },
  { name: "Trek Fuel EXe", specs: { voltage: 50, capacityAh: 7.2, motorWatts: 250, bikeWeightLbs: 41, tireType: 'knobby', controllerType: 'TQ' } },
  { name: "Segway Ninebot Max G2", specs: { voltage: 36, capacityAh: 15.3, motorWatts: 450, bikeWeightLbs: 53, tireType: 'road', controllerType: 'Standard' } },
  { name: "Dualtron Thunder 3", specs: { voltage: 72, capacityAh: 40, motorWatts: 2500, bikeWeightLbs: 126, tireType: 'road', controllerType: 'Sine Wave' } },
  { name: "Nami Burn-E 2 Max", specs: { voltage: 72, capacityAh: 40, motorWatts: 1500, bikeWeightLbs: 103, tireType: 'road', controllerType: 'Sine Wave' } },
  { name: "Inmotion RS", specs: { voltage: 72, capacityAh: 40, motorWatts: 2000, bikeWeightLbs: 128, tireType: 'road', controllerType: 'FOC' } }
];

// 100 Top Sold Pedal E-Bikes (US, CA, UK)
export const PEDAL_EBIKES_US_UK_CA: SavedBike[] = [
  { name: "Rad Power Radster Road", specs: { voltage: 48, capacityAh: 15, motorWatts: 750, bikeWeightLbs: 74.5, tireType: "road", controllerType: "48V 25A" } },
  { name: "Rad Power Radster Trail", specs: { voltage: 48, capacityAh: 15, motorWatts: 750, bikeWeightLbs: 77.5, tireType: "knobby", controllerType: "48V 25A" } },
  { name: "Rad Power RadWagon 5", specs: { voltage: 48, capacityAh: 15, motorWatts: 750, bikeWeightLbs: 86, tireType: "road", controllerType: "48V 25A" } },
  { name: "Rad Power RadExpand 5 Plus", specs: { voltage: 48, capacityAh: 15, motorWatts: 750, bikeWeightLbs: 62.5, tireType: "road", controllerType: "48V 25A" } },
  { name: "Aventon Level.2", specs: { voltage: 48, capacityAh: 14, motorWatts: 500, bikeWeightLbs: 62, tireType: "road", controllerType: "Sine Wave" } },
  { name: "Aventon Aventure.2", specs: { voltage: 48, capacityAh: 15, motorWatts: 750, bikeWeightLbs: 77, tireType: "knobby", controllerType: "Sine Wave" } },
  { name: "Aventon Soltera.2", specs: { voltage: 36, capacityAh: 9.6, motorWatts: 350, bikeWeightLbs: 46, tireType: "road", controllerType: "Standard" } },
  { name: "Aventon Pace 500.3", specs: { voltage: 48, capacityAh: 12.8, motorWatts: 500, bikeWeightLbs: 52, tireType: "road", controllerType: "Sine Wave" } },
  { name: "Aventon Ramblas", specs: { voltage: 36, capacityAh: 19.6, motorWatts: 250, bikeWeightLbs: 54, tireType: "knobby", controllerType: "Mid-Drive Integrated" } },
  { name: "Lectric XP 3.0", specs: { voltage: 48, capacityAh: 10.4, motorWatts: 500, bikeWeightLbs: 64, tireType: "knobby", controllerType: "20A Sine Wave" } },
  { name: "Lectric ONE", specs: { voltage: 48, capacityAh: 10.4, motorWatts: 750, bikeWeightLbs: 55, tireType: "road", controllerType: "24A Sine Wave" } },
  { name: "Lectric XPeak", specs: { voltage: 48, capacityAh: 14, motorWatts: 750, bikeWeightLbs: 71, tireType: "knobby", controllerType: "24A Sine Wave" } },
  { name: "Lectric XP Lite 2.0", specs: { voltage: 48, capacityAh: 7.8, motorWatts: 300, bikeWeightLbs: 47, tireType: "road", controllerType: "15A Sine Wave" } },
  { name: "Specialized Turbo Vado 4.0", specs: { voltage: 36, capacityAh: 19.7, motorWatts: 250, bikeWeightLbs: 58, tireType: "road", controllerType: "Specialized 2.0" } },
  { name: "Specialized Turbo Levo SL Comp", specs: { voltage: 48, capacityAh: 6.6, motorWatts: 240, bikeWeightLbs: 41, tireType: "knobby", controllerType: "Specialized SL 1.1" } },
  { name: "Specialized Turbo Como SL 5.0", specs: { voltage: 48, capacityAh: 6.6, motorWatts: 240, bikeWeightLbs: 48.5, tireType: "road", controllerType: "Specialized SL 1.1" } },
  { name: "Specialized Turbo Tero 3.0", specs: { voltage: 36, capacityAh: 14.7, motorWatts: 250, bikeWeightLbs: 51, tireType: "knobby", controllerType: "Specialized 2.0E" } },
  { name: "Specialized Turbo Creo 2 Comp", specs: { voltage: 48, capacityAh: 6.6, motorWatts: 250, bikeWeightLbs: 32, tireType: "road", controllerType: "Specialized SL 1.2" } },
  { name: "Trek Marlin+ 6", specs: { voltage: 36, capacityAh: 11.1, motorWatts: 250, bikeWeightLbs: 49.5, tireType: "knobby", controllerType: "Bosch Performance Line" } },
  { name: "Trek FX+ 2", specs: { voltage: 36, capacityAh: 7, motorWatts: 250, bikeWeightLbs: 40, tireType: "road", controllerType: "Hyena" } },
  { name: "Trek Rail 7 Gen 2", specs: { voltage: 36, capacityAh: 17.4, motorWatts: 250, bikeWeightLbs: 53, tireType: "knobby", controllerType: "Bosch Performance CX" } },
  { name: "Trek Allant+ 8S", specs: { voltage: 36, capacityAh: 17.4, motorWatts: 250, bikeWeightLbs: 56, tireType: "road", controllerType: "Bosch Performance Speed" } },
  { name: "Giant Explore E+ 2", specs: { voltage: 36, capacityAh: 17.4, motorWatts: 250, bikeWeightLbs: 55, tireType: "road", controllerType: "SyncDrive Sport" } },
  { name: "Giant Talon E+ 3", specs: { voltage: 36, capacityAh: 11.1, motorWatts: 250, bikeWeightLbs: 48, tireType: "knobby", controllerType: "SyncDrive Core" } },
  { name: "Giant Reign E+ 1", specs: { voltage: 36, capacityAh: 22.2, motorWatts: 250, bikeWeightLbs: 54, tireType: "knobby", controllerType: "SyncDrive Pro" } },
  { name: "Giant Trance X E+ 2", specs: { voltage: 36, capacityAh: 17.4, motorWatts: 250, bikeWeightLbs: 53, tireType: "knobby", controllerType: "SyncDrive Pro" } },
  { name: "Ride1Up CF Racer1", specs: { voltage: 36, capacityAh: 7, motorWatts: 250, bikeWeightLbs: 28, tireType: "road", controllerType: "Integrated Sine" } },
  { name: "Ride1Up Revv 1 DRT", specs: { voltage: 52, capacityAh: 20, motorWatts: 1000, bikeWeightLbs: 94, tireType: "knobby", controllerType: "28A Sine Wave" } },
  { name: "Ride1Up Portola", specs: { voltage: 48, capacityAh: 10.4, motorWatts: 750, bikeWeightLbs: 59, tireType: "road", controllerType: "18A Sine Wave" } },
  { name: "Ride1Up LMT'D V2", specs: { voltage: 48, capacityAh: 14, motorWatts: 750, bikeWeightLbs: 55, tireType: "road", controllerType: "22A Sine Wave" } },
  { name: "Ride1Up 700 Series", specs: { voltage: 48, capacityAh: 15, motorWatts: 750, bikeWeightLbs: 62, tireType: "road", controllerType: "22A Sine Wave" } },
  { name: "Ride1Up Rift", specs: { voltage: 48, capacityAh: 20, motorWatts: 750, bikeWeightLbs: 84, tireType: "knobby", controllerType: "25A Sine Wave" } },
  { name: "Himiway C5", specs: { voltage: 48, capacityAh: 20, motorWatts: 750, bikeWeightLbs: 88, tireType: "knobby", controllerType: "Sine Wave" } },
  { name: "Himiway A7 Pro", specs: { voltage: 48, capacityAh: 15, motorWatts: 500, bikeWeightLbs: 68, tireType: "road", controllerType: "Mid-Drive Integrated" } },
  { name: "Himiway Zebra Premium", specs: { voltage: 48, capacityAh: 20, motorWatts: 750, bikeWeightLbs: 79, tireType: "knobby", controllerType: "22A Sine Wave" } },
  { name: "Himiway D7 Pro", specs: { voltage: 48, capacityAh: 20, motorWatts: 1000, bikeWeightLbs: 75, tireType: "knobby", controllerType: "30A Sine Wave" } },
  { name: "Juiced Scrambler X2", specs: { voltage: 52, capacityAh: 19.2, motorWatts: 750, bikeWeightLbs: 83, tireType: "knobby", controllerType: "25A Cadence" } },
  { name: "Juiced HyperScorpion", specs: { voltage: 52, capacityAh: 19.2, motorWatts: 1000, bikeWeightLbs: 102, tireType: "road", controllerType: "35A Torque" } },
  { name: "Juiced RipCurrent S", specs: { voltage: 52, capacityAh: 19.2, motorWatts: 1000, bikeWeightLbs: 76, tireType: "knobby", controllerType: "25A Torque" } },
  { name: "Juiced CrossCurrent X", specs: { voltage: 52, capacityAh: 19.2, motorWatts: 750, bikeWeightLbs: 65, tireType: "road", controllerType: "25A Torque" } },
  { name: "Velotric Discover 2", specs: { voltage: 48, capacityAh: 14.7, motorWatts: 750, bikeWeightLbs: 63, tireType: "road", controllerType: "FOC Sine Wave" } },
  { name: "Velotric Summit 1", specs: { voltage: 48, capacityAh: 14.7, motorWatts: 750, bikeWeightLbs: 62, tireType: "knobby", controllerType: "FOC Sine Wave" } },
  { name: "Velotric Fold 1", specs: { voltage: 48, capacityAh: 13, motorWatts: 750, bikeWeightLbs: 63, tireType: "knobby", controllerType: "Sine Wave" } },
  { name: "Velotric Nomad 1 Plus", specs: { voltage: 48, capacityAh: 14.4, motorWatts: 750, bikeWeightLbs: 73, tireType: "knobby", controllerType: "Sine Wave" } },
  { name: "Velotric T1 ST Plus", specs: { voltage: 36, capacityAh: 9.8, motorWatts: 350, bikeWeightLbs: 39, tireType: "road", controllerType: "Standard" } },
  { name: "Tenways CGO009", specs: { voltage: 36, capacityAh: 10.4, motorWatts: 250, bikeWeightLbs: 50, tireType: "road", controllerType: "FOC" } },
  { name: "Tenways CGO600 Pro", specs: { voltage: 36, capacityAh: 10, motorWatts: 350, bikeWeightLbs: 37, tireType: "road", controllerType: "FOC" } },
  { name: "Tenways AGO T", specs: { voltage: 36, capacityAh: 14, motorWatts: 250, bikeWeightLbs: 62, tireType: "road", controllerType: "Enviolo Optimized" } },
  { name: "Tenways AGO X", specs: { voltage: 36, capacityAh: 14, motorWatts: 250, bikeWeightLbs: 59, tireType: "road", controllerType: "Standard" } },
  { name: "Gazelle Eclipse C380 HMB", specs: { voltage: 36, capacityAh: 20.8, motorWatts: 250, bikeWeightLbs: 64, tireType: "road", controllerType: "Bosch Performance CX" } },
  { name: "Gazelle Ultimate C380 HMB", specs: { voltage: 36, capacityAh: 17.4, motorWatts: 250, bikeWeightLbs: 55, tireType: "road", controllerType: "Bosch Performance Line" } },
  { name: "Gazelle Medeo T10+ HMB", specs: { voltage: 36, capacityAh: 13.8, motorWatts: 250, bikeWeightLbs: 52, tireType: "road", controllerType: "Bosch Performance Line" } },
  { name: "Tern Orox S12", specs: { voltage: 36, capacityAh: 22.2, motorWatts: 250, bikeWeightLbs: 74, tireType: "knobby", controllerType: "Bosch Performance CX" } },
  { name: "Tern GSD S10", specs: { voltage: 36, capacityAh: 11.1, motorWatts: 250, bikeWeightLbs: 74, tireType: "road", controllerType: "Bosch Cargo Line" } },
  { name: "Tern HSD P5i", specs: { voltage: 36, capacityAh: 13.8, motorWatts: 250, bikeWeightLbs: 56, tireType: "road", controllerType: "Bosch Performance Line" } },
  { name: "Heybike Hero", specs: { voltage: 48, capacityAh: 18, motorWatts: 750, bikeWeightLbs: 75, tireType: "knobby", controllerType: "Sine Wave" } },
  { name: "Heybike Horizon", specs: { voltage: 48, capacityAh: 14.4, motorWatts: 750, bikeWeightLbs: 79, tireType: "knobby", controllerType: "Sine Wave" } },
  { name: "Heybike Mars 2.0", specs: { voltage: 48, capacityAh: 12.5, motorWatts: 750, bikeWeightLbs: 75, tireType: "knobby", controllerType: "Standard" } },
  { name: "Blix Ultra", specs: { voltage: 48, capacityAh: 14, motorWatts: 750, bikeWeightLbs: 76, tireType: "knobby", controllerType: "Sine Wave" } },
  { name: "Blix Packa Genie", specs: { voltage: 48, capacityAh: 12.8, motorWatts: 750, bikeWeightLbs: 81, tireType: "road", controllerType: "Standard" } },
  { name: "Biktrix Juggernaut XD", specs: { voltage: 52, capacityAh: 17.5, motorWatts: 2300, bikeWeightLbs: 95, tireType: "knobby", controllerType: "XD Drive" } },
  { name: "Biktrix Juggernaut FS Pro 3", specs: { voltage: 52, capacityAh: 17.5, motorWatts: 1000, bikeWeightLbs: 85, tireType: "knobby", controllerType: "Sine Wave" } },
  { name: "Volt Pulse (UK)", specs: { voltage: 36, capacityAh: 14, motorWatts: 250, bikeWeightLbs: 53, tireType: "road", controllerType: "SpinTech" } },
  { name: "Raleigh Motus Grand Tour (UK)", specs: { voltage: 36, capacityAh: 13.8, motorWatts: 250, bikeWeightLbs: 56, tireType: "road", controllerType: "Bosch Active Line" } },
  { name: "Brompton Electric P Line (UK)", specs: { voltage: 36, capacityAh: 8.4, motorWatts: 250, bikeWeightLbs: 34.4, tireType: "road", controllerType: "Brompton Custom" } },
  { name: "MiRiDER One GB3 (UK)", specs: { voltage: 36, capacityAh: 7, motorWatts: 250, bikeWeightLbs: 43, tireType: "road", controllerType: "MiRiDER Custom" } },
  { name: "Surface 604 Colt", specs: { voltage: 48, capacityAh: 20, motorWatts: 500, bikeWeightLbs: 63, tireType: "road", controllerType: "Sine Wave" } },
  { name: "Surface 604 Shred", specs: { voltage: 48, capacityAh: 20, motorWatts: 500, bikeWeightLbs: 64, tireType: "knobby", controllerType: "Sine Wave" } },
  { name: "Envo D50", specs: { voltage: 48, capacityAh: 14, motorWatts: 750, bikeWeightLbs: 62, tireType: "road", controllerType: "Standard" } },
  { name: "VoltBike Yukon 750 Ltd (CAN)", specs: { voltage: 48, capacityAh: 19.6, motorWatts: 750, bikeWeightLbs: 70, tireType: "knobby", controllerType: "Sine Wave" } },
  { name: "Ribble Allroad SL R e (UK)", specs: { voltage: 36, capacityAh: 6.9, motorWatts: 250, bikeWeightLbs: 26, tireType: "road", controllerType: "Mahle X20" } },
  { name: "Estarli e20.7 Pro (UK)", specs: { voltage: 36, capacityAh: 7, motorWatts: 250, bikeWeightLbs: 38.5, tireType: "road", controllerType: "Standard" } },
  { name: "Ariel Rider Kepler", specs: { voltage: 52, capacityAh: 20, motorWatts: 1000, bikeWeightLbs: 73, tireType: "knobby", controllerType: "33A Sine Wave" } },
  { name: "Rad Power RadCity 5 Plus", specs: { voltage: 48, capacityAh: 14, motorWatts: 750, bikeWeightLbs: 65, tireType: "road", controllerType: "Custom Sine" } },
  { name: "Rad Power RadRover 6 Plus", specs: { voltage: 48, capacityAh: 14, motorWatts: 750, bikeWeightLbs: 73, tireType: "knobby", controllerType: "Custom Sine" } },
  { name: "Aventon Sinch.2", specs: { voltage: 48, capacityAh: 14, motorWatts: 500, bikeWeightLbs: 68, tireType: "knobby", controllerType: "Sine Wave" } },
  { name: "Aventon Abound", specs: { voltage: 48, capacityAh: 15, motorWatts: 750, bikeWeightLbs: 81, tireType: "road", controllerType: "Sine Wave" } },
  { name: "Lectric XPedition", specs: { voltage: 48, capacityAh: 14, motorWatts: 750, bikeWeightLbs: 75, tireType: "road", controllerType: "Sine Wave" } },
  { name: "Ride1Up Cafe Cruiser", specs: { voltage: 48, capacityAh: 15, motorWatts: 750, bikeWeightLbs: 65, tireType: "road", controllerType: "Sine Wave" } },
  { name: "Ride1Up Roadster V2", specs: { voltage: 36, capacityAh: 7, motorWatts: 350, bikeWeightLbs: 33, tireType: "road", controllerType: "Standard" } },
  { name: "Ride1Up Prodigy V2", specs: { voltage: 36, capacityAh: 14, motorWatts: 250, bikeWeightLbs: 58, tireType: "road", controllerType: "Brose Integrated" } },
  { name: "Himiway Cruiser", specs: { voltage: 48, capacityAh: 17.5, motorWatts: 750, bikeWeightLbs: 72, tireType: "knobby", controllerType: "Sine Wave" } },
  { name: "Himiway Cobra", specs: { voltage: 48, capacityAh: 20, motorWatts: 750, bikeWeightLbs: 88, tireType: "knobby", controllerType: "Sine Wave" } },
  { name: "Velotric Discover 1", specs: { voltage: 48, capacityAh: 14.4, motorWatts: 500, bikeWeightLbs: 65, tireType: "road", controllerType: "Standard" } },
  { name: "Velotric Packer 1", specs: { voltage: 48, capacityAh: 14.4, motorWatts: 750, bikeWeightLbs: 75, tireType: "road", controllerType: "Sine Wave" } },
  { name: "Tenways CGO800S", specs: { voltage: 36, capacityAh: 10.4, motorWatts: 250, bikeWeightLbs: 51, tireType: "road", controllerType: "FOC" } },
  { name: "Gazelle Arroyo C8 HMB", specs: { voltage: 36, capacityAh: 13.8, motorWatts: 250, bikeWeightLbs: 54, tireType: "road", controllerType: "Bosch Active Line" } },
  { name: "Tern Quick Haul P9", specs: { voltage: 36, capacityAh: 11.1, motorWatts: 250, bikeWeightLbs: 50, tireType: "road", controllerType: "Bosch Performance Line" } },
  { name: "Heybike Ranger S", specs: { voltage: 48, capacityAh: 14.4, motorWatts: 750, bikeWeightLbs: 72, tireType: "knobby", controllerType: "Sine Wave" } },
  { name: "Heybike Tyson", specs: { voltage: 48, capacityAh: 15, motorWatts: 750, bikeWeightLbs: 77, tireType: "knobby", controllerType: "Sine Wave" } },
  { name: "Blix Vika X", specs: { voltage: 48, capacityAh: 12.8, motorWatts: 500, bikeWeightLbs: 55, tireType: "road", controllerType: "Standard" } },
  { name: "Blix Sol X", specs: { voltage: 48, capacityAh: 12.8, motorWatts: 750, bikeWeightLbs: 56, tireType: "road", controllerType: "Standard" } },
  { name: "Biktrix Stunner SO 6", specs: { voltage: 48, capacityAh: 21, motorWatts: 750, bikeWeightLbs: 65, tireType: "road", controllerType: "Sine Wave" } },
  { name: "QuietKat Apex Pro", specs: { voltage: 48, capacityAh: 17.5, motorWatts: 1000, bikeWeightLbs: 70, tireType: "knobby", controllerType: "VPO Technology" } },
  { name: "VanMoof S5", specs: { voltage: 48, capacityAh: 9.6, motorWatts: 250, bikeWeightLbs: 50.7, tireType: "road", controllerType: "VanMoof Custom" } },
  { name: "Cowboy Cruiser", specs: { voltage: 36, capacityAh: 10, motorWatts: 250, bikeWeightLbs: 42.5, tireType: "road", controllerType: "Cowboy Adaptive" } },
  { name: "Cannondale Adventure Neo 3 EQ", specs: { voltage: 36, capacityAh: 11.1, motorWatts: 250, bikeWeightLbs: 56, tireType: "road", controllerType: "Bosch Active Line" } },
  { name: "Canyon Roadlite:ON CF 9", specs: { voltage: 36, capacityAh: 11.1, motorWatts: 250, bikeWeightLbs: 33, tireType: "road", controllerType: "Fazua Ride 60" } },
  { name: "Orbea Gain M30", specs: { voltage: 36, capacityAh: 9.8, motorWatts: 250, bikeWeightLbs: 25.5, tireType: "road", controllerType: "Mahle X20" } },
  { name: "Surface 604 Rook", specs: { voltage: 48, capacityAh: 20, motorWatts: 500, bikeWeightLbs: 63, tireType: "road", controllerType: "Sine Wave" } },
  { name: "Specialized Turbo Vado 3.0", specs: { voltage: 36, capacityAh: 14.7, motorWatts: 250, bikeWeightLbs: 55, tireType: "road", controllerType: "Specialized 2.0E" } },
  { name: "Trek Allant+ 7", specs: { voltage: 36, capacityAh: 13.8, motorWatts: 250, bikeWeightLbs: 54, tireType: "road", controllerType: "Bosch Performance Line" } },
  { name: "Giant AnyTour E+ 1", specs: { voltage: 36, capacityAh: 17.4, motorWatts: 250, bikeWeightLbs: 58, tireType: "road", controllerType: "SyncDrive Sport" } }
];

// 100 Top Sold E-Motos & High-Power E-Bikes
export const E_MOTOS_GLOBAL: SavedBike[] = [
  { name: "Surron Light Bee X", specs: { voltage: 60, capacityAh: 40, motorWatts: 3000, bikeWeightLbs: 126, tireType: "knobby", controllerType: "Sine Wave" } },
  { name: "Surron Ultra Bee", specs: { voltage: 74, capacityAh: 55, motorWatts: 6000, bikeWeightLbs: 187, tireType: "knobby", controllerType: "Sine Wave" } },
  { name: "Surron Storm Bee", specs: { voltage: 96, capacityAh: 48, motorWatts: 10000, bikeWeightLbs: 260, tireType: "knobby", controllerType: "Sine Wave" } },
  { name: "Talaria Sting R MX4", specs: { voltage: 60, capacityAh: 45, motorWatts: 4000, bikeWeightLbs: 145, tireType: "knobby", controllerType: "FOC" } },
  { name: "Talaria Sting MX5", specs: { voltage: 72, capacityAh: 40, motorWatts: 5500, bikeWeightLbs: 167, tireType: "knobby", controllerType: "FOC" } },
  { name: "Talaria Dragon", specs: { voltage: 88, capacityAh: 60, motorWatts: 10000, bikeWeightLbs: 220, tireType: "knobby", controllerType: "FOC" } },
  { name: "Talaria XXX", specs: { voltage: 60, capacityAh: 40, motorWatts: 2500, bikeWeightLbs: 125, tireType: "road", controllerType: "FOC" } },
  { name: "Stark Varg (80hp)", specs: { voltage: 360, capacityAh: 16.6, motorWatts: 40000, bikeWeightLbs: 260, tireType: "knobby", controllerType: "Proprietary FOC" } },
  { name: "Stark Varg EX", specs: { voltage: 360, capacityAh: 16.6, motorWatts: 40000, bikeWeightLbs: 264, tireType: "knobby", controllerType: "Proprietary FOC" } },
  { name: "Zero S (2025)", specs: { voltage: 102, capacityAh: 141, motorWatts: 11000, bikeWeightLbs: 492, tireType: "road", controllerType: "Cipher III" } },
  { name: "Zero SR (2025)", specs: { voltage: 102, capacityAh: 153, motorWatts: 15000, bikeWeightLbs: 492, tireType: "road", controllerType: "Cipher III" } },
  { name: "Zero SR/F", specs: { voltage: 102, capacityAh: 170, motorWatts: 40000, bikeWeightLbs: 518, tireType: "road", controllerType: "Cipher III" } },
  { name: "Zero SR/S", specs: { voltage: 102, capacityAh: 170, motorWatts: 40000, bikeWeightLbs: 518, tireType: "road", controllerType: "Cipher III" } },
  { name: "Zero FXE", specs: { voltage: 102, capacityAh: 71, motorWatts: 15000, bikeWeightLbs: 298, tireType: "road", controllerType: "Cipher II" } },
  { name: "Zero FX", specs: { voltage: 102, capacityAh: 71, motorWatts: 15000, bikeWeightLbs: 289, tireType: "knobby", controllerType: "Cipher II" } },
  { name: "Zero DSR/X", specs: { voltage: 102, capacityAh: 170, motorWatts: 36000, bikeWeightLbs: 545, tireType: "road", controllerType: "Cipher III" } },
  { name: "Zero XB (2025)", specs: { voltage: 74, capacityAh: 32, motorWatts: 3000, bikeWeightLbs: 139, tireType: "knobby", controllerType: "Cipher II" } },
  { name: "Zero XE (2025)", specs: { voltage: 74, capacityAh: 58, motorWatts: 6000, bikeWeightLbs: 223, tireType: "knobby", controllerType: "Cipher II" } },
  { name: "Energica Ego+ RS", specs: { voltage: 300, capacityAh: 72, motorWatts: 110000, bikeWeightLbs: 573, tireType: "road", controllerType: "VCU V3" } },
  { name: "Energica Eva Ribelle", specs: { voltage: 300, capacityAh: 72, motorWatts: 110000, bikeWeightLbs: 573, tireType: "road", controllerType: "VCU V3" } },
  { name: "Energica EsseEsse9+", specs: { voltage: 300, capacityAh: 72, motorWatts: 80000, bikeWeightLbs: 573, tireType: "road", controllerType: "VCU V3" } },
  { name: "Energica Experia", specs: { voltage: 300, capacityAh: 75, motorWatts: 60000, bikeWeightLbs: 573, tireType: "road", controllerType: "VCU V3" } },
  { name: "Super Soco TC Max", specs: { voltage: 72, capacityAh: 45, motorWatts: 3900, bikeWeightLbs: 222, tireType: "road", controllerType: "FOC" } },
  { name: "Super Soco TS Street Hunter", specs: { voltage: 60, capacityAh: 32, motorWatts: 2500, bikeWeightLbs: 227, tireType: "road", controllerType: "FOC" } },
  { name: "VMoto Stash", specs: { voltage: 74, capacityAh: 97, motorWatts: 9000, bikeWeightLbs: 337, tireType: "road", controllerType: "FOC" } },
  { name: "VMoto ON-R", specs: { voltage: 72, capacityAh: 48, motorWatts: 4000, bikeWeightLbs: 187, tireType: "road", controllerType: "FOC" } },
  { name: "VMoto OFF-R", specs: { voltage: 72, capacityAh: 48, motorWatts: 4000, bikeWeightLbs: 187, tireType: "knobby", controllerType: "FOC" } },
  { name: "Cake Bukk", specs: { voltage: 72, capacityAh: 40, motorWatts: 8500, bikeWeightLbs: 196, tireType: "knobby", controllerType: "Proprietary FOC" } },
  { name: "Cake Kalk OR", specs: { voltage: 51.8, capacityAh: 50, motorWatts: 5000, bikeWeightLbs: 152, tireType: "knobby", controllerType: "Standard FOC" } },
  { name: "Cake Kalk&", specs: { voltage: 51.8, capacityAh: 50, motorWatts: 5000, bikeWeightLbs: 174, tireType: "road", controllerType: "Standard FOC" } },
  { name: "Cake Ösa+", specs: { voltage: 50.4, capacityAh: 70, motorWatts: 7000, bikeWeightLbs: 202, tireType: "road", controllerType: "Standard FOC" } },
  { name: "Cake Makka Flex", specs: { voltage: 48, capacityAh: 31, motorWatts: 2800, bikeWeightLbs: 154, tireType: "road", controllerType: "Standard FOC" } },
  { name: "LiveWire One", specs: { voltage: 102, capacityAh: 151, motorWatts: 60000, bikeWeightLbs: 562, tireType: "road", controllerType: "Revelation" } },
  { name: "LiveWire S2 Del Mar", specs: { voltage: 102, capacityAh: 103, motorWatts: 30000, bikeWeightLbs: 436, tireType: "road", controllerType: "S2 Custom" } },
  { name: "BMW CE 04", specs: { voltage: 148, capacityAh: 60, motorWatts: 15000, bikeWeightLbs: 509, tireType: "road", controllerType: "BMW Proprietary" } },
  { name: "BMW CE 02", specs: { voltage: 48, capacityAh: 40, motorWatts: 6000, bikeWeightLbs: 291, tireType: "road", controllerType: "BMW Proprietary" } },
  { name: "Yadea Keeness", specs: { voltage: 72, capacityAh: 32, motorWatts: 5500, bikeWeightLbs: 350, tireType: "road", controllerType: "FOC" } },
  { name: "NIU RQi", specs: { voltage: 72, capacityAh: 72, motorWatts: 7500, bikeWeightLbs: 410, tireType: "road", controllerType: "FOC" } },
  { name: "Can-Am Origin", specs: { voltage: 102, capacityAh: 87, motorWatts: 35000, bikeWeightLbs: 412, tireType: "knobby", controllerType: "Rotax E-Power" } },
  { name: "Can-Am Pulse", specs: { voltage: 102, capacityAh: 87, motorWatts: 35000, bikeWeightLbs: 390, tireType: "road", controllerType: "Rotax E-Power" } },
  { name: "Ryvid Anthem", specs: { voltage: 72, capacityAh: 60, motorWatts: 7500, bikeWeightLbs: 313, tireType: "road", controllerType: "ASI BAC" } },
  { name: "Ryvid Outset", specs: { voltage: 72, capacityAh: 60, motorWatts: 7500, bikeWeightLbs: 315, tireType: "road", controllerType: "ASI BAC" } },
  { name: "Evoke 6061-GT", specs: { voltage: 292, capacityAh: 102, motorWatts: 90000, bikeWeightLbs: 705, tireType: "road", controllerType: "Evoke ECU" } },
  { name: "Horwin CR6", specs: { voltage: 72, capacityAh: 55, motorWatts: 6200, bikeWeightLbs: 295, tireType: "road", controllerType: "FOC" } },
  { name: "Maeving RM1S", specs: { voltage: 51, capacityAh: 106, motorWatts: 7200, bikeWeightLbs: 293, tireType: "road", controllerType: "Standard FOC" } },
  { name: "Kawasaki Ninja e-1", specs: { voltage: 50, capacityAh: 60, motorWatts: 5000, bikeWeightLbs: 308, tireType: "road", controllerType: "Kawasaki Custom" } },
  { name: "Lightning LS-218", specs: { voltage: 380, capacityAh: 52, motorWatts: 112000, bikeWeightLbs: 495, tireType: "road", controllerType: "Custom High-Voltage" } },
  { name: "Verge TS Ultra", specs: { voltage: 102, capacityAh: 198, motorWatts: 100000, bikeWeightLbs: 540, tireType: "road", controllerType: "Hub Motor Controller" } },
  { name: "Damon HyperSport", specs: { voltage: 450, capacityAh: 44, motorWatts: 100000, bikeWeightLbs: 440, tireType: "road", controllerType: "HyperDrive" } },
  { name: "Ultraviolette F77 Mach 2", specs: { voltage: 103, capacityAh: 100, motorWatts: 10000, bikeWeightLbs: 434, tireType: "road", controllerType: "Proprietary FOC" } },
  { name: "Ola S1 Pro Gen 2", specs: { voltage: 48, capacityAh: 84, motorWatts: 5500, bikeWeightLbs: 275, tireType: "road", controllerType: "Standard" } },
  { name: "Tromox MC10", specs: { voltage: 72, capacityAh: 58, motorWatts: 5000, bikeWeightLbs: 198, tireType: "knobby", controllerType: "FOC" } },
  { name: "Rawrr Mantis X", specs: { voltage: 72, capacityAh: 30, motorWatts: 3000, bikeWeightLbs: 139, tireType: "knobby", controllerType: "FOC" } },
  { name: "Rawrr Mantis S", specs: { voltage: 72, capacityAh: 35, motorWatts: 4500, bikeWeightLbs: 173, tireType: "knobby", controllerType: "FOC" } },
  { name: "Arctic Leopard E-XE 880", specs: { voltage: 90, capacityAh: 75, motorWatts: 15000, bikeWeightLbs: 238, tireType: "knobby", controllerType: "Proprietary FOC" } },
  { name: "Arctic Leopard E-XE 800", specs: { voltage: 90, capacityAh: 58, motorWatts: 12000, bikeWeightLbs: 231, tireType: "knobby", controllerType: "Proprietary FOC" } },
  { name: "Arctic Leopard E-XT 700", specs: { voltage: 72, capacityAh: 60, motorWatts: 8000, bikeWeightLbs: 183, tireType: "knobby", controllerType: "Proprietary FOC" } },
  { name: "Arctic Leopard E-XT 500", specs: { voltage: 72, capacityAh: 30, motorWatts: 5000, bikeWeightLbs: 159, tireType: "knobby", controllerType: "Proprietary FOC" } },
  { name: "E-Ride Pro SS (3.0)", specs: { voltage: 72, capacityAh: 50, motorWatts: 8000, bikeWeightLbs: 139, tireType: "knobby", controllerType: "FOC" } },
  { name: "E-Ride Pro SS (2.0)", specs: { voltage: 72, capacityAh: 40, motorWatts: 6000, bikeWeightLbs: 139, tireType: "knobby", controllerType: "FOC" } },
  { name: "E-Ride Pro S", specs: { voltage: 72, capacityAh: 30, motorWatts: 3000, bikeWeightLbs: 128, tireType: "knobby", controllerType: "FOC" } },
  { name: "Gowow Ori", specs: { voltage: 73.8, capacityAh: 38.4, motorWatts: 4500, bikeWeightLbs: 161, tireType: "knobby", controllerType: "FOC" } },
  { name: "Velimotors VMX08", specs: { voltage: 72, capacityAh: 45, motorWatts: 3000, bikeWeightLbs: 105, tireType: "knobby", controllerType: "FOC" } },
  { name: "Sondors Metacycle", specs: { voltage: 72, capacityAh: 55, motorWatts: 8000, bikeWeightLbs: 300, tireType: "road", controllerType: "Standard FOC" } },
  { name: "Volcon Grunt EVO", specs: { voltage: 60, capacityAh: 38, motorWatts: 4000, bikeWeightLbs: 285, tireType: "knobby", controllerType: "Proprietary" } },
  { name: "Volcon Runt LT", specs: { voltage: 60, capacityAh: 16.6, motorWatts: 2000, bikeWeightLbs: 147, tireType: "knobby", controllerType: "Proprietary" } },
  { name: "Volcon Brat", specs: { voltage: 48, capacityAh: 15.6, motorWatts: 750, bikeWeightLbs: 86, tireType: "knobby", controllerType: "Sine Wave" } },
  { name: "UBCO 2X2 Adventure", specs: { voltage: 50, capacityAh: 42, motorWatts: 2000, bikeWeightLbs: 156, tireType: "knobby", controllerType: "Dual Drive FOC" } },
  { name: "UBCO 2X2 Work", specs: { voltage: 50, capacityAh: 62, motorWatts: 2000, bikeWeightLbs: 156, tireType: "knobby", controllerType: "Dual Drive FOC" } },
  { name: "Land Moto District (Street)", specs: { voltage: 72, capacityAh: 64, motorWatts: 11500, bikeWeightLbs: 245, tireType: "road", controllerType: "Land Custom" } },
  { name: "Land Moto District (Scrambler)", specs: { voltage: 72, capacityAh: 64, motorWatts: 11500, bikeWeightLbs: 245, tireType: "knobby", controllerType: "Land Custom" } },
  { name: "Kollter ES1-S Pro", specs: { voltage: 72, capacityAh: 64, motorWatts: 5000, bikeWeightLbs: 298, tireType: "road", controllerType: "FOC" } },
  { name: "Trevor FDT", specs: { voltage: 72, capacityAh: 37.5, motorWatts: 8000, bikeWeightLbs: 223, tireType: "road", controllerType: "Motech Custom" } },
  { name: "RGNT No. 1 Classic", specs: { voltage: 72, capacityAh: 80, motorWatts: 9000, bikeWeightLbs: 350, tireType: "road", controllerType: "RGNT V3" } },
  { name: "RGNT No. 1 Scrambler", specs: { voltage: 72, capacityAh: 80, motorWatts: 9000, bikeWeightLbs: 350, tireType: "knobby", controllerType: "RGNT V3" } },
  { name: "Tromox Ukko S", specs: { voltage: 72, capacityAh: 55, motorWatts: 4000, bikeWeightLbs: 242, tireType: "road", controllerType: "FOC" } },
  { name: "Tromox Mino", specs: { voltage: 60, capacityAh: 31, motorWatts: 1200, bikeWeightLbs: 149, tireType: "road", controllerType: "Standard" } },
  { name: "Horwin CR6 Pro", specs: { voltage: 72, capacityAh: 55, motorWatts: 6200, bikeWeightLbs: 304, tireType: "road", controllerType: "FOC" } },
  { name: "Horwin HT5", specs: { voltage: 72, capacityAh: 48, motorWatts: 3500, bikeWeightLbs: 196, tireType: "knobby", controllerType: "FOC" } },
  { name: "Maeving RM1", specs: { voltage: 50.4, capacityAh: 40, motorWatts: 3000, bikeWeightLbs: 245, tireType: "road", controllerType: "FOC" } },
  { name: "Ultraviolette F77 Mach 2 Recon", specs: { voltage: 96, capacityAh: 107, motorWatts: 9500, bikeWeightLbs: 456, tireType: "road", controllerType: "Proprietary FOC" } },
  { name: "KTM Freeride E-XC", specs: { voltage: 260, capacityAh: 15, motorWatts: 9000, bikeWeightLbs: 245, tireType: "knobby", controllerType: "KTM Custom" } },
  { name: "Evoke Urban Classic", specs: { voltage: 103.6, capacityAh: 72.9, motorWatts: 11000, bikeWeightLbs: 395, tireType: "road", controllerType: "Evoke ECU" } },
  { name: "Tacita T-Cruise Urban", specs: { voltage: 120, capacityAh: 150, motorWatts: 11000, bikeWeightLbs: 461, tireType: "road", controllerType: "Tacita Custom" } },
  { name: "Soco TS Hunter", specs: { voltage: 60, capacityAh: 32, motorWatts: 2500, bikeWeightLbs: 225, tireType: "road", controllerType: "FOC" } },
  { name: "Soco TC Wanderer", specs: { voltage: 60, capacityAh: 32, motorWatts: 2500, bikeWeightLbs: 220, tireType: "knobby", controllerType: "FOC" } },
  { name: "Niu NQi GTS", specs: { voltage: 60, capacityAh: 26, motorWatts: 3000, bikeWeightLbs: 230, tireType: "road", controllerType: "FOC" } },
  { name: "Niu MQi GT Evo", specs: { voltage: 72, capacityAh: 26, motorWatts: 5000, bikeWeightLbs: 240, tireType: "road", controllerType: "FOC" } },
  { name: "Super Soco CPx", specs: { voltage: 60, capacityAh: 45, motorWatts: 4000, bikeWeightLbs: 235, tireType: "road", controllerType: "FOC" } },
  { name: "Horwin EK3", specs: { voltage: 72, capacityAh: 36, motorWatts: 6200, bikeWeightLbs: 210, tireType: "road", controllerType: "FOC" } },
  { name: "Cake Makka Range", specs: { voltage: 48, capacityAh: 31, motorWatts: 1800, bikeWeightLbs: 150, tireType: "road", controllerType: "Standard FOC" } },
  { name: "Aventon Level 2 Commuter", specs: { voltage: 48, capacityAh: 14, motorWatts: 500, bikeWeightLbs: 62, tireType: "road", controllerType: "Sine Wave" } },
  { name: "Ride1Up Revv 1", specs: { voltage: 52, capacityAh: 20, motorWatts: 750, bikeWeightLbs: 93, tireType: "road", controllerType: "Sine Wave" } },
  { name: "Juiced RipCurrent S Step-Through", specs: { voltage: 52, capacityAh: 19.2, motorWatts: 1000, bikeWeightLbs: 76, tireType: "knobby", controllerType: "Torque" } },
  { name: "Rad Power RadRunner 3 Plus", specs: { voltage: 48, capacityAh: 14, motorWatts: 750, bikeWeightLbs: 75, tireType: "knobby", controllerType: "Custom Sine" } },
  { name: "Lectric XP Step-Thru 3.0", specs: { voltage: 48, capacityAh: 10.4, motorWatts: 500, bikeWeightLbs: 64, tireType: "knobby", controllerType: "Sine Wave" } },
  { name: "Blix Packa Genie Cargo", specs: { voltage: 48, capacityAh: 12.8, motorWatts: 750, bikeWeightLbs: 81, tireType: "road", controllerType: "Standard" } },
  { name: "Tern GSD S00", specs: { voltage: 36, capacityAh: 13.8, motorWatts: 250, bikeWeightLbs: 74, tireType: "road", controllerType: "Bosch Cargo Line" } },
  { name: "Specialized Turbo Vado IGH", specs: { voltage: 36, capacityAh: 19.7, motorWatts: 250, bikeWeightLbs: 58, tireType: "road", controllerType: "Specialized 2.2" } }
];
